package cryptox

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"io"
	"os"
	"testing"
)

// chunkedFixture is generated by the WEB APP's production TypeScript
// implementation (quibit-mvp scripts, src/lib/crypto/chunked.ts) —
// decrypting it here proves byte-level cross-implementation
// compatibility, not just Go-round-trips-Go.
type chunkedFixture struct {
	Version            string `json:"version"`
	ChunkSizeBytes     int    `json:"chunkSizeBytes"`
	ChunkOverheadBytes int    `json:"chunkOverheadBytes"`
	FileKeyBase64      string `json:"fileKeyBase64"`
	PlaintextBase64    string `json:"plaintextBase64"`
	CiphertextBase64   string `json:"ciphertextBase64"`
}

func loadFixture(t *testing.T) (fx chunkedFixture, fileKey, plaintext, ciphertext []byte) {
	t.Helper()
	raw, err := os.ReadFile("testdata/chunked_v2_fixture.json")
	if err != nil {
		t.Fatalf("reading fixture: %v", err)
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	mustB64 := func(s string) []byte {
		b, err := base64.StdEncoding.DecodeString(s)
		if err != nil {
			t.Fatalf("fixture base64: %v", err)
		}
		return b
	}
	return fx, mustB64(fx.FileKeyBase64), mustB64(fx.PlaintextBase64), mustB64(fx.CiphertextBase64)
}

func TestDecryptChunkedStream_WebFixture(t *testing.T) {
	fx, fileKey, plaintext, ciphertext := loadFixture(t)
	if fx.Version != ChunkedEncryptionVersion {
		t.Fatalf("fixture version %q != %q", fx.Version, ChunkedEncryptionVersion)
	}
	if fx.ChunkOverheadBytes != chunkOverheadBytes {
		t.Fatalf("overhead drift: fixture %d, Go %d", fx.ChunkOverheadBytes, chunkOverheadBytes)
	}

	var out bytes.Buffer
	n, err := DecryptChunkedStream(fileKey, fx.ChunkSizeBytes, bytes.NewReader(ciphertext), &out)
	if err != nil {
		t.Fatalf("DecryptChunkedStream: %v", err)
	}
	if n != int64(len(plaintext)) {
		t.Fatalf("wrote %d bytes, want %d", n, len(plaintext))
	}
	if !bytes.Equal(out.Bytes(), plaintext) {
		t.Fatal("plaintext mismatch against web-generated fixture")
	}
}

// The stream decryptor must work regardless of how the reader chops
// up the bytes (network reads are arbitrary). iotest-style 1-byte
// reader is the worst case.
func TestDecryptChunkedStream_OneByteReads(t *testing.T) {
	fx, fileKey, plaintext, ciphertext := loadFixture(t)
	var out bytes.Buffer
	oneByte := iotest{r: bytes.NewReader(ciphertext)}
	if _, err := DecryptChunkedStream(fileKey, fx.ChunkSizeBytes, &oneByte, &out); err != nil {
		t.Fatalf("DecryptChunkedStream: %v", err)
	}
	if !bytes.Equal(out.Bytes(), plaintext) {
		t.Fatal("plaintext mismatch under 1-byte reads")
	}
}

type iotest struct{ r io.Reader }

func (o *iotest) Read(p []byte) (int, error) {
	if len(p) > 1 {
		p = p[:1]
	}
	return o.r.Read(p)
}

func TestChunkedRoundTrip(t *testing.T) {
	fileKey := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, fileKey); err != nil {
		t.Fatal(err)
	}
	const chunkSize = 1024
	// 3 full chunks + partial last; also an exact-multiple case.
	for _, ptLen := range []int{chunkSize*3 + 41, chunkSize * 2, 1} {
		plaintext := make([]byte, ptLen)
		if _, err := io.ReadFull(rand.Reader, plaintext); err != nil {
			t.Fatal(err)
		}
		count := (ptLen + chunkSize - 1) / chunkSize
		var blob bytes.Buffer
		for i := 0; i < count; i++ {
			end := (i + 1) * chunkSize
			if end > ptLen {
				end = ptLen
			}
			enc, err := EncryptChunk(fileKey, plaintext[i*chunkSize:end], i, i == count-1)
			if err != nil {
				t.Fatalf("EncryptChunk: %v", err)
			}
			blob.Write(enc)
		}
		wantSize, err := CiphertextSizeForPlaintext(int64(ptLen), chunkSize)
		if err != nil {
			t.Fatal(err)
		}
		if int64(blob.Len()) != wantSize {
			t.Fatalf("ciphertext size %d, want %d (ptLen=%d)", blob.Len(), wantSize, ptLen)
		}
		var out bytes.Buffer
		if _, err := DecryptChunkedStream(fileKey, chunkSize, bytes.NewReader(blob.Bytes()), &out); err != nil {
			t.Fatalf("decrypt (ptLen=%d): %v", ptLen, err)
		}
		if !bytes.Equal(out.Bytes(), plaintext) {
			t.Fatalf("round-trip mismatch (ptLen=%d)", ptLen)
		}
	}
}

// The AAD binding is the security core of the format: every
// manipulation of chunk order or count must fail closed.
func TestChunkedTamperRejected(t *testing.T) {
	fx, fileKey, _, ciphertext := loadFixture(t)
	encChunkLen := fx.ChunkSizeBytes + chunkOverheadBytes
	chunk := func(i int) []byte {
		start := i * encChunkLen
		end := start + encChunkLen
		if end > len(ciphertext) {
			end = len(ciphertext)
		}
		return ciphertext[start:end]
	}
	decrypt := func(blob []byte) error {
		_, err := DecryptChunkedStream(fileKey, fx.ChunkSizeBytes, bytes.NewReader(blob), io.Discard)
		return err
	}

	cat := func(parts ...[]byte) []byte {
		var b bytes.Buffer
		for _, p := range parts {
			b.Write(p)
		}
		return b.Bytes()
	}

	if err := decrypt(cat(chunk(1), chunk(0), chunk(2))); err == nil {
		t.Fatal("reordered chunks decrypted — AAD index binding is broken")
	}
	if err := decrypt(cat(chunk(0), chunk(1))); err == nil {
		t.Fatal("truncated blob decrypted — AAD last-flag binding is broken")
	}
	if err := decrypt(cat(chunk(0), chunk(0), chunk(2))); err == nil {
		t.Fatal("duplicated chunk decrypted — AAD index binding is broken")
	}
	flipped := append([]byte(nil), ciphertext...)
	flipped[len(flipped)/2] ^= 0x01
	if err := decrypt(flipped); err == nil {
		t.Fatal("bit-flipped blob decrypted — GCM auth is broken")
	}
	if err := decrypt(chunk(2)); err == nil {
		t.Fatal("final chunk alone decrypted at index 0 — AAD index binding is broken")
	}
}

func TestPrepareChunkedUpload(t *testing.T) {
	pubB64, priv := genKeypair(t)
	prep, err := PrepareChunkedUpload("video.mp4", pubB64, DefaultChunkSizeBytes)
	if err != nil {
		t.Fatalf("PrepareChunkedUpload: %v", err)
	}
	defer func() {
		for i := range prep.FileKey {
			prep.FileKey[i] = 0
		}
	}()

	// The wrap must unwrap back to the same file key with the standard
	// v1.1+ path — chunked files change the CONTENT format only.
	unwrapped, err := UnwrapFileKey(priv, prep.EncapsulatedKeyB64, prep.WrappedFileKeyB64, prep.KeyWrapNonceB64)
	if err != nil {
		t.Fatalf("UnwrapFileKey: %v", err)
	}
	if !bytes.Equal(unwrapped, prep.FileKey) {
		t.Fatal("unwrapped file key differs from prepared key")
	}

	// Filename decrypts under the file key (no AAD, same as v1.2).
	name, err := DecryptName(prep.FileKey, prep.EncryptedFilenameB64, prep.FilenameNonceB64)
	if err != nil {
		t.Fatalf("DecryptName: %v", err)
	}
	if name != "video.mp4" {
		t.Fatalf("filename round-trip: got %q", name)
	}

	// Content encrypted under the prepared key decrypts back.
	enc, err := EncryptChunk(prep.FileKey, []byte("hello chunked world"), 0, true)
	if err != nil {
		t.Fatal(err)
	}
	plain, err := DecryptChunk(prep.FileKey, enc, 0, true)
	if err != nil {
		t.Fatal(err)
	}
	if string(plain) != "hello chunked world" {
		t.Fatal("chunk round-trip under prepared key failed")
	}
}
